hydra:
  run:
    dir: 'train_experiment/${now:%Y-%m-%d}/${now:%H-%M}'
  output_subdir: 'yamls'

dataset_module:
  num_workers: 4
  dataset_root: "/path/to/dataset"

nn_module:
  lr: 0.0001

training:
  max_epochs: 50
  wandb_project: "MusicModelling"
  with_gpu: false
  wandb_name: "TrainNeuralNetwork"
  early_stop:
    monitor: "val_loss"
    patience: 5
    mode: "min"
  model_name: "Neural Network: LSTM/GRU/R-Transformer"
  model:
    layers: 3
    embedding_dim: 88
    hidden_dim: 100
    d_model: 160
    h: 2
    rnn_type: "GRU"
    ksize: 6
    n_level: 3
    n: 1
    dropout: 0.1



test:
  path: "/path/to/save/checkpoint"