hydra:
  run:
    dir: 'train_experiment/${now:%Y-%m-%d}/${now:%H-%M}'
  output_subdir: 'yamls'

dataset_module:
  batch_size: 1
  num_workers: 4
  #dataset_root: "/home/arybs/ZZSN/polyphonic-music-modeling/data/dataset"
  dataset_root: "/home/aneta/Desktop/ZZSN/code/polyphonic-music-modeling/data/dataset"

nn_module:
  lr: 0.0001

training:
  max_epochs: 50
  wandb_project: "MusicModelling"
  with_gpu: false
  wandb_name: "TrainLSTM"
