hydra:
  run:
    dir: 'train_experiment/${now:%Y-%m-%d}/${now:%H-%M}'
  output_subdir: 'yamls'

dataset_module:
  batch_size: 1
  num_workers: 4
  #dataset_root: "/home/arybs/ZZSN/polyphonic-music-modeling/data/dataset"
  #dataset_root: "/home/aneta/Desktop/ZZSN/code/polyphonic-music-modeling/data/dataset"
  dataset_root: "/content/drive/MyDrive/polyphonic-music-modeling/data/dataset"

nn_module:
  lr: 0.0001

training:
  max_epochs: 50
  wandb_project: "MusicModelling"
  with_gpu: true
  wandb_name: "TrainLSTM"
  early_stop:
    monitor: "val_loss"
    patience: 5
    mode: "min"

test:
  path: /home/arybs/ZZSN/polyphonic-music-modeling/train_experiment/2022-05-23/01-06/lightning_logs/version_0/checkpoints/ # do udoskonalenia
